"""
Q‑code subject and status lookup tables

Based on ICAO Annex 15, Appendix 6 (NOTAM, AIP SUP and AIC Codes).
This file maps:
  - the two‑letter subject designator (2nd–3rd letters of the
    5‑character group after the leading "Q") to an (Area code,
    Sub‑Area, Signification) tuple,
  - the 4th letter of the Q‑code to its Condition category,
  - the two‑letter status/modifier designator (4th–5th letters)
    to its Signification string.
"""

# ── SUBJECT_MAP: SECOND & THIRD LETTERS ─────────────────────────────────────
# Key: 2‑letter code → (Area code, Sub‑Area, Signification)
SUBJECT_MAP = {
    # AGA – Lighting Facilities (L)
    "LA": ("AGA", "Lighting facilities", "Approach lighting system"),
    "LB": ("AGA", "Lighting facilities", "Aerodrome beacon abnormality"),
    "LC": ("AGA", "Lighting facilities", "Runway centre line lights"),
    "LD": ("AGA", "Lighting facilities", "Landing direction indicator lights"),
    "LE": ("AGA", "Lighting facilities", "Runway edge lights"),
    "LF": ("AGA", "Lighting facilities", "Sequenced flashing lights"),
    "LH": ("AGA", "Lighting facilities", "High intensity runway lights"),
    "LI": ("AGA", "Lighting facilities", "Runway end identifier lights"),
    "LJ": ("AGA", "Lighting facilities", "Runway alignment indicator lights"),
    "LK": ("AGA", "Lighting facilities", "Category II components of approach lighting system"),
    "LL": ("AGA", "Lighting facilities", "Low intensity runway lights"),
    "LM": ("AGA", "Lighting facilities", "Medium intensity runway lights"),
    "LP": ("AGA", "Lighting facilities", "Precision approach path indicator (PAPI)"),
    "LR": ("AGA", "Lighting facilities", "All landing area lighting facilities"),
    "LS": ("AGA", "Lighting facilities", "Stopway lights"),
    "LT": ("AGA", "Lighting facilities", "Threshold lights"),
    "LV": ("AGA", "Lighting facilities", "Visual approach slope indicator system"),
    "LW": ("AGA", "Lighting facilities", "Heliport lighting"),
    "LX": ("AGA", "Lighting facilities", "Taxiway centre line lights"),
    "LY": ("AGA", "Lighting facilities", "Taxiway edge lights"),
    "LZ": ("AGA", "Lighting facilities", "Runway touchdown zone lights"),

    # AGA – Movement and landing area (M)
    "MA": ("AGA", "Movement and landing area", "Movement area"),
    "MB": ("AGA", "Movement and landing area", "Bearing strength"),
    "MC": ("AGA", "Movement and landing area", "Clearway"),
    "MD": ("AGA", "Movement and landing area", "Declared distances"),
    "MG": ("AGA", "Movement and landing area", "Taxiing guidance system"),
    "MH": ("AGA", "Movement and landing area", "Runway arresting gear"),
    "MK": ("AGA", "Movement and landing area", "Parking area"),
    "MM": ("AGA", "Movement and landing area", "Daylight markings"),
    "MN": ("AGA", "Movement and landing area", "Apron"),
    "MP": ("AGA", "Movement and landing area", "Aircraft stands"),
    "MR": ("AGA", "Movement and landing area", "Runway"),
    "MS": ("AGA", "Movement and landing area", "Stopway"),
    "MT": ("AGA", "Movement and landing area", "Threshold"),
    "MU": ("AGA", "Movement and landing area", "Runway turning bay"),
    "MW": ("AGA", "Movement and landing area", "Strip"),
    "MX": ("AGA", "Movement and landing area", "Taxiway(s)"),

    # AGA – Facilities and services (F)
    "FA": ("AGA", "Facilities and services", "Aerodrome available/duty"),
    "FB": ("AGA", "Facilities and services", "Braking action measurement equipment"),
    "FC": ("AGA", "Facilities and services", "Ceiling measurement equipment"),
    "FD": ("AGA", "Facilities and services", "Docking system"),
    "FF": ("AGA", "Facilities and services", "Fire fighting and rescue"),
    "FG": ("AGA", "Facilities and services", "Ground movement control"),
    "FH": ("AGA", "Facilities and services", "Helicopter alighting area/platform"),
    "FL": ("AGA", "Facilities and services", "Landing direction indicator"),
    "FM": ("AGA", "Facilities and services", "Meteorological service"),
    "FO": ("AGA", "Facilities and services", "Fog dispersal system"),
    "FP": ("AGA", "Facilities and services", "Heliport"),
    "FS": ("AGA", "Facilities and services", "Snow removal equipment"),
    "FT": ("AGA", "Facilities and services", "Transmissometer"),
    "FU": ("AGA", "Facilities and services", "Fuel availability"),
    "FW": ("AGA", "Facilities and services", "Wind direction indicator"),
    "FZ": ("AGA", "Facilities and services", "Customs"),

    # COM – Communications & radar (C)
    "CA": ("COM", "Communications and radar", "Air/ground service"),
    "CE": ("COM", "Communications and radar", "En route surveillance radar"),
    "CG": ("COM", "Communications and radar", "Ground controlled approach system (GCA)"),
    "CL": ("COM", "Communications and radar", "Selective calling system (SELCAL)"),
    "CM": ("COM", "Communications and radar", "Surface movement radar"),
    "CP": ("COM", "Communications and radar", "Precision approach radar (PAR)"),
    "CR": ("COM", "Communications and radar", "Surveillance radar element of PAR system"),
    "CS": ("COM", "Communications and radar", "Secondary surveillance radar (SSR)"),
    "CT": ("COM", "Communications and radar", "Terminal area surveillance radar (TAR)"),
    "CB": ("COM", "Communications and radar", "VHF communication"),
    "CC": ("COM", "Communications and radar", "UHF communication"),
    "CD": ("COM", "Communications and radar", "Data link service"),
    "CF": ("COM", "Communications and radar", "Secondary surveillance radar (SSR) [alt]") ,

    # COM – Instrument and MLS (I)
    "ID": ("COM", "Instrument and MLS", "DME associated with ILS"),
    "IG": ("COM", "Instrument and MLS", "Glide path (ILS)"),
    "II": ("COM", "Instrument and MLS", "Inner marker (ILS)"),
    "IL": ("COM", "Instrument and MLS", "Localizer (ILS)"),
    "IM": ("COM", "Instrument and MLS", "Middle marker (ILS)"),
    "IO": ("COM", "Instrument and MLS", "Outer marker (ILS)"),
    "IS": ("COM", "Instrument and MLS", "ILS Category I"),
    "IT": ("COM", "Instrument and MLS", "ILS Category II"),
    "IU": ("COM", "Instrument and MLS", "ILS Category III"),
    "IW": ("COM", "Instrument and MLS", "Microwave landing system (MLS)"),
    "IX": ("COM", "Instrument and MLS", "Locator, outer (ILS)"),
    "IY": ("COM", "Instrument and MLS", "Locator, middle (ILS)"),

    # COM – En route navigation (N)
    "NA": ("COM", "En route navigation", "All radio navigation facilities"),
    "NB": ("COM", "En route navigation", "Nondirectional radio beacon"),
    "NC": ("COM", "En route navigation", "DECCA"),
    "ND": ("COM", "En route navigation", "Distance measuring equipment (DME)"),
    "NF": ("COM", "En route navigation", "Fan marker"),
    "NL": ("COM", "En route navigation", "Locator"),
    "NM": ("COM", "En route navigation", "VOR/DME"),
    "NN": ("COM", "En route navigation", "TACAN"),
    "NO": ("COM", "En route navigation", "OMEGA"),
    "NT": ("COM", "En route navigation", "VORTAC"),
    "NV": ("COM", "En route navigation", "VOR"),
    "NX": ("COM", "En route navigation", "Direction finding station"),

    # AIS – Aeronautical information service (IA)
    "IA": ("AIS", "Aeronautical information service", "AIP amendment"),
    "IB": ("AIS", "Aeronautical information service", "AIP supplement"),
    "IC": ("AIS", "Aeronautical information service", "AIC bulletin"),

    # RAC – Airspace organization (A)
    "AA": ("ATM", "Airspace organization", "Minimum altitude"),
    "AC": ("ATM", "Airspace organization", "Class B, C, D, or E surface area"),
    "AD": ("ATM", "Airspace organization", "Air defense identification zone (ADIZ)"),
    "AE": ("RAC – Airspace Org", "Control area (CTA)"),
    "AF": ("RAC – Airspace Org", "Flight information region (FIR)"),
    "AH": ("RAC – Airspace Org", "Upper control area (UTA)"),
    "AL": ("RAC – Airspace Org", "Minimum usable flight level"),
    "AN": ("RAC – Airspace Org", "Area navigation route"),
    "AO": ("RAC – Airspace Org", "Oceanic control area (OCA)"),
    "AP": ("RAC – Airspace Org", "Reporting point "),
    "AR": ("RAC – Airspace Org", "ATS route "),
    "AT": ("RAC – Airspace Org", "Class B Airspace"),
    "AU": ("RAC – Airspace Org", "Upper flight information region (UIR)"),
    "AV": ("RAC – Airspace Org", "Upper advisory area (UDA)"),
    "AX": ("RAC – Airspace Org", "Intersection (INT)"),
    "AZ": ("RAC – Airspace Org", "Aerodrome traffic zone (ATZ)"),
    
     # RAC – Air Traffic & VOLMET Services (S)
    "SA": ("RAC – ATS/VolMET", "Automatic terminal information service (ATIS)"),
    "SB": ("RAC – ATS/VolMET", "ATS reporting office"),
    "SC": ("RAC – ATS/VolMET", "Area control centre (ACC)"),
    "SE": ("RAC – ATS/VolMET", "Flight information service (FIS)"),
    "SF": ("RAC – ATS/VolMET", "Aerodrome flight information service (AFIS)"),
    "SL": ("RAC – ATS/VolMET", "Flow control centre"),
    "SO": ("RAC – ATS/VolMET", "Oceanic area control centre (OAC)"),
    "SP": ("RAC – ATS/VolMET", "Approach control service (APP)"),
    "SS": ("RAC – ATS/VolMET", "Flight service station (FSS)"),
    "ST": ("RAC – ATS/VolMET", "Aerodrome control tower (TWR)"),
    "SU": ("RAC – ATS/VolMET", "Upper area control centre (UAC)"),
    "SV": ("RAC – ATS/VolMET", "VOLMET broadcast"),
    "SY": ("RAC – ATS/VolMET", "Upper advisory service "),

    # RAC – Air Traffic Procedures (P)
    "PA": ("RAC – Procedures", "Standard instrument arrival (STAR) "),
    "PD": ("RAC – Procedures", "Standard instrument departure (SID) "),
    "PF": ("RAC – Procedures", "Flow control procedure"),
    "PH": ("RAC – Procedures", "Holding procedure"),
    "PI": ("RAC – Procedures", "Instrument approach procedure "),
    "PL": ("RAC – Procedures", "Obstacle clearance limit "),
    "PM": ("RAC – Procedures", "Aerodrome operating minima "),
    "PO": ("RAC – Procedures", "Obstacle clearance altitude"),
    "PP": ("RAC – Procedures", "Obstacle clearance height"),
    "PR": ("RAC – Procedures", "Radio failure procedure"),
    "PT": ("RAC – Procedures", "Transition altitude"),
    "PU": ("RAC – Procedures", "Missed approach procedure "),
    "PX": ("RAC – Procedures", "Minimum holding altitude "),
    "PZ": ("RAC – Procedures", "ADIZ procedure"),

    # Navigation Warnings – Airspace Restrictions (R)
    "RA": ("Navigation Warnings – Restrictions", "Airspace reservation "),
    "RD": ("Navigation Warnings – Restrictions", "Danger area "),
    "RO": ("Navigation Warnings – Restrictions", "Overflying of "),
    "RP": ("Navigation Warnings – Restrictions", "Prohibited area "),
    "RR": ("Navigation Warnings – Restrictions", "Restricted area "),
    "RT": ("Navigation Warnings – Restrictions", "Temporary restricted area"),

    # Navigation Warnings – Warnings (W)
    "WA": ("Navigation Warnings – Warnings", "Air display"),
    "WB": ("Navigation Warnings – Warnings", "Aerobatics"),
    "WC": ("Navigation Warnings – Warnings", "Captive balloon or kite"),
    "WD": ("Navigation Warnings – Warnings", "Demolition of explosives"),
    "WE": ("Navigation Warnings – Warnings", "Exercises "),
    "WF": ("Navigation Warnings – Warnings", "Air refuelling"),
    "WG": ("Navigation Warnings – Warnings", "Glider flying"),
    "WJ": ("Navigation Warnings – Warnings", "Banner/target towing"),
    "WL": ("Navigation Warnings – Warnings", "Ascent of free balloon"),
    "WM": ("Navigation Warnings – Warnings", "Missile, gun or rocket firing"),
    "WP": ("Navigation Warnings – Warnings", "Parachute jumping exercise (PJE)"),
    "WS": ("Navigation Warnings – Warnings", "Burning or blowing gas"),
    "WT": ("Navigation Warnings – Warnings", "Mass movement of aircraft"),
    "WV": ("Navigation Warnings – Warnings", "Formation flight"),
    "WZ": ("Navigation Warnings – Warnings", "Model flying"),

    # Other Information (O)
    "OA": ("Other Information", "Aeronautical information service"),
    "OB": ("Other Information", "Obstacle "),
    "OE": ("Other Information", "Aircraft entry requirements"),
    "OL": ("Other Information", "Obstacle lights on "),
    "OR": ("Other Information", "Rescue coordination centre"),
    
    # ——— Missing codes to match ICAO JSON ———
    "KK": ("Other Information", "NOTAM Checklist"),
    "MO": ("AGA",               "Stopbar"),
    "WU": ("Navigation Warnings","Unmanned aircraft"),
    "WY": ("Navigation Warnings","Aerial survey"),
    "XX": ("Other Information", "Not listed"),
}

# ── CONDITION_MAP: FOURTH LETTER ────────────────────────────────────────────
# Key: 4th letter of Q‑code → Condition category
CONDITION_MAP = {
    "A": "Availability",
    "C": "Changes",
    "H": "Hazard Conditions",
    "L": "Limitations",
    "X": "Other",
    "K": "Not Defined",          
    "T": "Other",
    "B": "Availability",    
    "D": "Availability",     
    "K": "Other",            
    "M": "Other",    
}

# ── STATUS_MAP: FOURTH & FIFTH LETTERS ──────────────────────────────────────
# Key: 2‑letter code → Signification
STATUS_MAP = {
    # Availability (A)
    "AC": "Withdrawn for maintenance",
    "AD": "Available for daylight operation",
    "AF": "Flight checked and found reliable",
    "AG": "Operating but ground checked only, awaiting flight check",
    "AH": "Hours of service are now",
    "AK": "Resumed normal operations",
    "AM": "Military operations only",
    "AN": "Available for night operation",
    "AO": "Operational",
    "AP": "Available, prior permission required",
    "AR": "Available on request",
    "AS": "Unserviceable",
    "AU": "Not available",
    "AW": "Completely withdrawn",
    "AX": "Previously promulgated shutdown has been cancelled",

    # Changes (C)
    "CA": "Activated",
    "CC": "Completed",
    "CD": "Deactivated",
    "CE": "Erected",
    "CF": "Operating on reduced power",
    "CG": "Downgraded to",
    "CH": "Changed",
    "CI": "Identification or call sign changed",
    "CL": "Realigned",
    "CM": "Displaced",
    "CO": "Operating",
    "CP": "Operating on reduced power",
    "CR": "Temporarily replaced by",
    "CS": "Installed",
    "CT": "On test, do not use",

    # Hazard Conditions (H)
    "HA": "Braking action is",
    "HB": "Braking coefficient is",
    "HC": "Covered by compacted snow to depth of",
    "HD": "Covered by dry snow to a depth of",
    "HE": "Covered by water to a depth of",
    "HF": "Totally free of snow and ice",
    "HG": "Grass cutting in progress",
    "HH": "Hazard due to ",
    "HI": "Covered by ice",
    "HJ": "Launch planned ",
    "HK": "Migration in progress",
    "HL": "Snow clearance completed",
    "HM": "Marked by",
    "HN": "Covered by wet snow or slush to a depth of",
    "HO": "Obscured by snow",
    "HP": "Snow clearance in progress",
    "HQ": "Operation cancelled ",
    "HR": "Standing water",
    "HS": "Sanding in progress",
    "HT": "Approach according to signal area only",
    "HU": "Launch in progress ",
    "HV": "Work completed",
    "HW": "Work in progress",
    "HX": "Concentration of birds",
    "HY": "Snow banks exist",
    "HZ": "Covered by frozen ruts and ridges",

    # Limitations (L)
    "LA": "Operating on auxiliary power supply",
    "LB": "Reserved for aircraft based therein",
    "LC": "Closed",
    "LD": "Unsafe",
    "LE": "Operating without auxiliary power",
    "LF": "Interference from",
    "LG": "Operating without identification",
    "LH": "Unserviceable for aircraft heavier than",
    "LI": "Closed to IFR operations",
    "LK": "Operating as a fixed light",
    "LL": "Usable for length of...and width of...",
    "LN": "Closed to all night operations",
    "LP": "Prohibited to",
    "LR": "Aircraft restricted to runways and taxiways",
    "LS": "Subject to interruption",
    "LT": "Limited to",
    "LV": "Closed to VFR operations",
    "LW": "Will take place",
    "LX": "Operating but caution advised",

    # Other (XX)
    "XX": "Plain language",
    "KK": "Not Defined",                         
    "TT": "AIRAC AIP Amendments", 
    
    "BF": "Plain language",  
    "DF": "Plain language",
    "KR": "Plain language",
    "MF": "Plain language",
}
