"""
Q‑code subject and status lookup tables

Based on ICAO Annex 15, Appendix 6 (NOTAM, AIP SUP and AIC Codes).
This file maps the two‑letter subject designator (2nd–3rd letters of the
5‑character group after the leading "Q") to an (Area, Sub‑Area) tuple,
and maps the status/modifier designator (4th–5th letters) to its
Signification string.
"""

# ── SUBJECT_MAP: SECOND & THIRD LETTERS ──────────────────────────────────────
# Key: 2‑letter code → (Area bucket, Signification)
SUBJECT_MAP = {
    # AGA – Lighting Facilities (L)
    "LA": ("AGA – Lighting Facilities", "Approach lighting system "),
    "LB": ("AGA – Lighting Facilities", "Aerodrome beacon abnormality"),
    "LC": ("AGA – Lighting Facilities", "Runway centre line lights "),
    "LD": ("AGA – Lighting Facilities", "Landing direction indicator lights"),
    "LE": ("AGA – Lighting Facilities", "Runway edge lights "),
    "LF": ("AGA – Lighting Facilities", "Sequenced flashing lights "),
    "LH": ("AGA – Lighting Facilities", "High intensity runway lights "),
    "LI": ("AGA – Lighting Facilities", "Runway end identifier lights "),
    "LJ": ("AGA – Lighting Facilities", "Runway alignment indicator lights "),
    "LK": ("AGA – Lighting Facilities", "Category II components of approach lighting system "),
    "LL": ("AGA – Lighting Facilities", "Low intensity runway lights "),
    "LM": ("AGA – Lighting Facilities", "Medium intensity runway lights "),
    "LP": ("AGA – Lighting Facilities", "Precision approach path indicator (PAPI) "),
    "LR": ("AGA – Lighting Facilities", "All landing area lighting facilities"),
    "LS": ("AGA – Lighting Facilities", "Stopway lights "),
    "LT": ("AGA – Lighting Facilities", "Threshold lights "),
    "LV": ("AGA – Lighting Facilities", "Visual approach slope indicator system "),
    "LW": ("AGA – Lighting Facilities", "Heliport lighting"),
    "LX": ("AGA – Lighting Facilities", "Taxiway centre line lights "),
    "LY": ("AGA – Lighting Facilities", "Taxiway edge lights "),
    "LZ": ("AGA – Lighting Facilities", "Runway touchdown zone lights "),

    # AGA – Movement and Landing Area (M)
    "MA": ("AGA – Movement & Landing Area", "Movement area"),
    "MB": ("AGA – Movement & Landing Area", "Bearing strength "),
    "MC": ("AGA – Movement & Landing Area", "Clearway "),
    "MD": ("AGA – Movement & Landing Area", "Declared distances "),
    "MG": ("AGA – Movement & Landing Area", "Taxiing guidance system"),
    "MH": ("AGA – Movement & Landing Area", "Runway arresting gear "),
    "MK": ("AGA – Movement & Landing Area", "Parking area"),
    "MM": ("AGA – Movement & Landing Area", "Daylight markings "),
    "MN": ("AGA – Movement & Landing Area", "Apron"),
    "MP": ("AGA – Movement & Landing Area", "Aircraft stands "),
    "MR": ("AGA – Movement & Landing Area", "Runway "),
    "MS": ("AGA – Movement & Landing Area", "Stopway "),
    "MT": ("AGA – Movement & Landing Area", "Threshold "),
    "MU": ("AGA – Movement & Landing Area", "Runway turning bay "),
    "MW": ("AGA – Movement & Landing Area", "Strip "),
    "MX": ("AGA – Movement & Landing Area", "Taxiway(s) "),

    # AGA – Facilities and Services (F)
    "FA": ("AGA – Facilities & Services", "Aerodrome available/duty"),
    "FB": ("AGA – Facilities & Services", "Braking action measurement equipment "),
    "FC": ("AGA – Facilities & Services", "Ceiling measurement equipment"),
    "FD": ("AGA – Facilities & Services", "Docking system "),
    "FF": ("AGA – Facilities & Services", "Fire fighting and rescue"),
    "FG": ("AGA – Facilities & Services", "Ground movement control"),
    "FH": ("AGA – Facilities & Services", "Helicopter alighting area/platform"),
    "FL": ("AGA – Facilities & Services", "Landing direction indicator"),
    "FM": ("AGA – Facilities & Services", "Meteorological service "),
    "FO": ("AGA – Facilities & Services", "Fog dispersal system"),
    "FP": ("AGA – Facilities & Services", "Heliport"),
    "FS": ("AGA – Facilities & Services", "Snow removal equipment"),
    "FT": ("AGA – Facilities & Services", "Transmissometer "),
    "FU": ("AGA – Facilities & Services", "Fuel availability"),
    "FW": ("AGA – Facilities & Services", "Wind direction indicator"),
    "FZ": ("AGA – Facilities & Services", "Customs"),

    # COM – Communications & Radar Facilities (C)
    "CA": ("COM – Comms & Radar", "Air/ground service "),
    "CE": ("COM – Comms & Radar", "En route surveillance radar"),
    "CG": ("COM – Comms & Radar", "Ground controlled approach system (GCA)"),
    "CL": ("COM – Comms & Radar", "Selective calling system (SELCAL)"),
    "CM": ("COM – Comms & Radar", "Surface movement radar"),
    "CP": ("COM – Comms & Radar", "Precision approach radar (PAR) "),
    "CR": ("COM – Comms & Radar", "Surveillance radar element of precision approach radar system"),
    "CS": ("COM – Comms & Radar", "Secondary surveillance radar (SSR)"),
    "CT": ("COM – Comms & Radar", "Terminal area surveillance radar (TAR)"),
    "CB": ("COM – Comms & Radar", "VHF communication"),
    "CC": ("COM – Comms & Radar", "UHF communication"),
    "CD": ("COM – Comms & Radar", "Data link service"),
    "CF": ("COM – Comms & Radar", "Secondary surveillance radar (SSR)"),

    # COM – Instrument & MLS (I)
    "ID": ("COM – Instrument & MLS", "DME associated with ILS"),
    "IG": ("COM – Instrument & MLS", "Glide path (ILS) "),
    "II": ("COM – Instrument & MLS", "Inner marker (ILS) "),
    "IL": ("COM – Instrument & MLS", "Localizer (ILS) "),
    "IM": ("COM – Instrument & MLS", "Middle marker (ILS) "),
    "IO": ("COM – Instrument & MLS", "Outer marker (ILS) "),
    "IS": ("COM – Instrument & MLS", "ILS Category I "),
    "IT": ("COM – Instrument & MLS", "ILS Category II "),
    "IU": ("COM – Instrument & MLS", "ILS Category III "),
    "IW": ("COM – Instrument & MLS", "Microwave landing system (MLS) "),
    "IX": ("COM – Instrument & MLS", "Locator, outer (ILS) "),
    "IY": ("COM – Instrument & MLS", "Locator, middle (ILS) "),

    # COM – En Route Navigation (N)
    "NA": ("COM – Nav Facilities", "All radio navigation facilities"),
    "NB": ("COM – Nav Facilities", "Nondirectional radio beacon"),
    "NC": ("COM – Nav Facilities", "DECCA"),
    "ND": ("COM – Nav Facilities", "Distance measuring equipment (DME)"),
    "NF": ("COM – Nav Facilities", "Fan marker"),
    "NL": ("COM – Nav Facilities", "Locator "),
    "NM": ("COM – Nav Facilities", "VOR/DME"),
    "NN": ("COM – Nav Facilities", "TACAN"),
    "NO": ("COM – Nav Facilities", "OMEGA"),
    "NT": ("COM – Nav Facilities", "VORTAC"),
    "NV": ("COM – Nav Facilities", "VOR"),
    "NX": ("COM – Nav Facilities", "Direction finding station "),
    
    # ── AIS – Aeronautical Information Service ───────────────────────────────────
    "IA": ("AIS – Aeronautical Information Service", "AIP amendment"),
    "IB": ("AIS – Aeronautical Information Service", "AIP supplement"),
    "IC": ("AIS – Aeronautical Information Service", "AIC bulletin"),

    # RAC – Airspace Organization (A)
    "AA": ("RAC – Airspace Org", "Minimum altitude"),
    "AC": ("RAC – Airspace Org", "Class B, C, D, or E Surface Area"),
    "AD": ("RAC – Airspace Org", "Air defense identification zone (ADIZ)"),
    "AE": ("RAC – Airspace Org", "Control area (CTA)"),
    "AF": ("RAC – Airspace Org", "Flight information region (FIR)"),
    "AH": ("RAC – Airspace Org", "Upper control area (UTA)"),
    "AL": ("RAC – Airspace Org", "Minimum usable flight level"),
    "AN": ("RAC – Airspace Org", "Area navigation route"),
    "AO": ("RAC – Airspace Org", "Oceanic control area (OCA)"),
    "AP": ("RAC – Airspace Org", "Reporting point "),
    "AR": ("RAC – Airspace Org", "ATS route "),
    "AT": ("RAC – Airspace Org", "Class B Airspace"),
    "AU": ("RAC – Airspace Org", "Upper flight information region (UIR)"),
    "AV": ("RAC – Airspace Org", "Upper advisory area (UDA)"),
    "AX": ("RAC – Airspace Org", "Intersection (INT)"),
    "AZ": ("RAC – Airspace Org", "Aerodrome traffic zone (ATZ)"),

    # RAC – Air Traffic & VOLMET Services (S)
    "SA": ("RAC – ATS/VolMET", "Automatic terminal information service (ATIS)"),
    "SB": ("RAC – ATS/VolMET", "ATS reporting office"),
    "SC": ("RAC – ATS/VolMET", "Area control centre (ACC)"),
    "SE": ("RAC – ATS/VolMET", "Flight information service (FIS)"),
    "SF": ("RAC – ATS/VolMET", "Aerodrome flight information service (AFIS)"),
    "SL": ("RAC – ATS/VolMET", "Flow control centre"),
    "SO": ("RAC – ATS/VolMET", "Oceanic area control centre (OAC)"),
    "SP": ("RAC – ATS/VolMET", "Approach control service (APP)"),
    "SS": ("RAC – ATS/VolMET", "Flight service station (FSS)"),
    "ST": ("RAC – ATS/VolMET", "Aerodrome control tower (TWR)"),
    "SU": ("RAC – ATS/VolMET", "Upper area control centre (UAC)"),
    "SV": ("RAC – ATS/VolMET", "VOLMET broadcast"),
    "SY": ("RAC – ATS/VolMET", "Upper advisory service "),

    # RAC – Air Traffic Procedures (P)
    "PA": ("RAC – Procedures", "Standard instrument arrival (STAR) "),
    "PD": ("RAC – Procedures", "Standard instrument departure (SID) "),
    "PF": ("RAC – Procedures", "Flow control procedure"),
    "PH": ("RAC – Procedures", "Holding procedure"),
    "PI": ("RAC – Procedures", "Instrument approach procedure "),
    "PL": ("RAC – Procedures", "Obstacle clearance limit "),
    "PM": ("RAC – Procedures", "Aerodrome operating minima "),
    "PO": ("RAC – Procedures", "Obstacle clearance altitude"),
    "PP": ("RAC – Procedures", "Obstacle clearance height"),
    "PR": ("RAC – Procedures", "Radio failure procedure"),
    "PT": ("RAC – Procedures", "Transition altitude"),
    "PU": ("RAC – Procedures", "Missed approach procedure "),
    "PX": ("RAC – Procedures", "Minimum holding altitude "),
    "PZ": ("RAC – Procedures", "ADIZ procedure"),

    # Navigation Warnings – Airspace Restrictions (R)
    "RA": ("Navigation Warnings – Restrictions", "Airspace reservation "),
    "RD": ("Navigation Warnings – Restrictions", "Danger area "),
    "RO": ("Navigation Warnings – Restrictions", "Overflying of "),
    "RP": ("Navigation Warnings – Restrictions", "Prohibited area "),
    "RR": ("Navigation Warnings – Restrictions", "Restricted area "),
    "RT": ("Navigation Warnings – Restrictions", "Temporary restricted area"),

    # Navigation Warnings – Warnings (W)
    "WA": ("Navigation Warnings – Warnings", "Air display"),
    "WB": ("Navigation Warnings – Warnings", "Aerobatics"),
    "WC": ("Navigation Warnings – Warnings", "Captive balloon or kite"),
    "WD": ("Navigation Warnings – Warnings", "Demolition of explosives"),
    "WE": ("Navigation Warnings – Warnings", "Exercises "),
    "WF": ("Navigation Warnings – Warnings", "Air refuelling"),
    "WG": ("Navigation Warnings – Warnings", "Glider flying"),
    "WJ": ("Navigation Warnings – Warnings", "Banner/target towing"),
    "WL": ("Navigation Warnings – Warnings", "Ascent of free balloon"),
    "WM": ("Navigation Warnings – Warnings", "Missile, gun or rocket firing"),
    "WP": ("Navigation Warnings – Warnings", "Parachute jumping exercise (PJE)"),
    "WS": ("Navigation Warnings – Warnings", "Burning or blowing gas"),
    "WT": ("Navigation Warnings – Warnings", "Mass movement of aircraft"),
    "WV": ("Navigation Warnings – Warnings", "Formation flight"),
    "WZ": ("Navigation Warnings – Warnings", "Model flying"),

    # Other Information (O)
    "OA": ("Other Information", "Aeronautical information service"),
    "OB": ("Other Information", "Obstacle "),
    "OE": ("Other Information", "Aircraft entry requirements"),
    "OL": ("Other Information", "Obstacle lights on "),
    "OR": ("Other Information", "Rescue coordination centre"),
}

# ── STATUS_MAP: FOURTH & FIFTH LETTERS ─────────────────────────────────────────
# Key: 2‑letter code → Signification
STATUS_MAP = {
    # Availability (A)
    "AC": "Withdrawn for maintenance",
    "AD": "Available for daylight operation",
    "AF": "Flight checked and found reliable",
    "AG": "Operating but ground checked only, awaiting flight check",
    "AH": "Hours of service are now",
    "AK": "Resumed normal operations",
    "AM": "Military operations only",
    "AN": "Available for night operation",
    "AO": "Operational",
    "AP": "Available, prior permission required",
    "AR": "Available on request",
    "AS": "Unserviceable",
    "AU": "Not available",
    "AW": "Completely withdrawn",
    "AX": "Previously promulgated shutdown has been cancelled",

    # Changes (C)
    "CA": "Activated",
    "CC": "Completed",
    "CD": "Deactivated",
    "CE": "Erected",
    "CF": "Operating frequency(ies) changed",
    "CG": "Downgraded to",
    "CH": "Changed",
    "CI": "Identification or call sign changed",
    "CL": "Realigned",
    "CM": "Displaced",
    "CO": "Operating",
    "CP": "Operating on reduced power",
    "CR": "Temporarily replaced by",
    "CS": "Installed",
    "CT": "On test, do not use",

    # Hazard Conditions (H)
    "HA": "Braking action is ",
    "HB": "Braking coefficient is ",
    "HC": "Covered by compacted snow to depth of",
    "HD": "Covered by dry snow to a depth of",
    "HE": "Covered by water to a depth of",
    "HF": "Totally free of snow and ice",
    "HG": "Grass cutting in progress",
    "HH": "Hazard due to ",
    "HI": "Covered by ice",
    "HJ": "Launch planned ",
    "HK": "Migration in progress",
    "HL": "Snow clearance completed",
    "HM": "Marked by",
    "HN": "Covered by wet snow or slush to a depth of",
    "HO": "Obscured by snow",
    "HP": "Snow clearance in progress",
    "HQ": "Operation cancelled ",
    "HR": "Standing water",
    "HS": "Sanding in progress",
    "HT": "Approach according to signal area only",
    "HU": "Launch in progress ",
    "HV": "Work completed",
    "HW": "Work in progress",
    "HX": "Concentration of birds",
    "HY": "Snow banks exist",
    "HZ": "Covered by frozen ruts and ridges",

    # Limitations (L)
    "LA": "Operating on auxiliary power supply",
    "LB": "Reserved for aircraft based therein",
    "LC": "Closed",
    "LD": "Unsafe",
    "LE": "Operating without auxiliary power",
    "LF": "Interference from",
    "LG": "Operating without identification",
    "LH": "Unserviceable for aircraft heavier than",
    "LI": "Closed to IFR operations",
    "LK": "Operating as a fixed light",
    "LL": "Usable for length of...and width of...",
    "LN": "Closed to all night operations",
    "LP": "Prohibited to",
    "LR": "Aircraft restricted to runways and taxiways",
    "LS": "Subject to interruption",
    "LT": "Limited to",
    "LV": "Closed to VFR operations",
    "LW": "Will take place",
    "LX": "Operating but caution advised",

    # Other (XX)
    "XX": "plain language",
}
